services:
  maria_dash:
    container_name: maria_dash
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - maria_db
    networks:
      - nw-default
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  maria_db:
    container_name: maria_db
    image: pgvector/pgvector:pg16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/shared/scripts/console-dump-maria_console.sql:/scripts/console-dump-maria_console.sql
      - ./src/shared/scripts/console-dump-extensions.sql:/scripts/console-dump-extensions.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - nw-default

volumes:
  postgres_data:

networks:
  nw-default:
    driver: bridge
    ipam:
      driver: default
